title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: rundocs/jekyll-rtd-theme

# Theme settings:
site_author: Vk 
repo_url: "https://github.com/ElektrikAkar/test_repoJekyll"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
logo: 'https://osqp.org/docs/_static/logo.png'
site_favicon: 'https://your.url/here.ico'
